language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

script:
  - docker-compose up -d
  - docker-compose ps
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)