language: java
jdk:
  - oraclejdk8

sudo: true

services:
  - docker
  - postgres

install: true

before_install:
  - docker-compose up --build -d postgres

script:
  - docker-compose up -d
  - docker-compose ps
  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker-compose down

cache:
  directories:
  - $HOME/.m2